name: "Node CI"
description: "Setup Node + pnpm + lint + build"

runs:
  using: "composite"
  steps:

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: "pnpm"

    - name: Install pnpm
      shell: bash
      run: |
        corepack enable
        pnpm -v

    - name: Install dependencies
      shell: bash
      run: pnpm install

    - name: Lint
      shell: bash
      run: pnpm lint

    - name: Build
      shell: bash
      run: pnpm build