name: "Node CI"
description: "Setup Node + pnpm + lint + build"

runs:
  using: "composite"
  steps:

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: "pnpm"

    - name: Enable pnpm via corepack & expose PATH
      shell: bash
      run: |
        corepack enable
        echo "$(corepack npm bin -g)" >> $GITHUB_PATH
        echo "PNPM version: $(pnpm -v)"

    - name: Install dependencies
      shell: bash
      run: pnpm install

    - name: Lint
      shell: bash
      run: pnpm lint

    - name: Build
      shell: bash
      run: pnpm build